---
name: CI
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - run: go install ./cmd/myaot
      - run: |
          set -eux
          myaot compile ./examples/hello-s/hello-riscv32
          [ "$(./a.out)" = "Hello World!" ]

  wasm:
    runs-on: ubuntu-22.04
    steps:
      - name: "Install Emscripten"
        run: |
          set -eux
          git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
          cd ~/emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - run: go install ./cmd/myaot
      - run: |
          set -eux
          myaot compile -o a.c ./examples/hello-s/hello-riscv32
          source ~/emsdk/emsdk_env.sh
          emcc -o a.wasm a.c
      # TODO: wasi
